-- MySQL Script generated by MySQL Workbench
-- Tue Sep 28 10:44:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIES` (
  `idCATEGORIES` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL,
  PRIMARY KEY (`idCATEGORIES`),
  UNIQUE INDEX `idCATEGORIES_UNIQUE` (`idCATEGORIES` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LIVRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LIVRE` (
  `idLIVRE` INT NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(255) NOT NULL,
  `Resume` LONGTEXT NOT NULL,
  `CATEGORIES_idCATEGORIES` INT NOT NULL,
  PRIMARY KEY (`idLIVRE`, `CATEGORIES_idCATEGORIES`),
  UNIQUE INDEX `idLIVRE_UNIQUE` (`idLIVRE` ASC) VISIBLE,
  UNIQUE INDEX `Titre_UNIQUE` (`Titre` ASC) VISIBLE,
  UNIQUE INDEX `Resume_UNIQUE` (`Resume` ASC) VISIBLE,
  INDEX `fk_LIVRE_CATEGORIES_idx` (`CATEGORIES_idCATEGORIES` ASC) VISIBLE,
  CONSTRAINT `fk_LIVRE_CATEGORIES`
    FOREIGN KEY (`CATEGORIES_idCATEGORIES`)
    REFERENCES `mydb`.`CATEGORIES` (`idCATEGORIES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AUTEUR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AUTEUR` (
  `idAUTEUR` INT NOT NULL AUTO_INCREMENT,
  `Date_of_birth` DATE NOT NULL,
  `Date_of_death` DATE NULL,
  PRIMARY KEY (`idAUTEUR`),
  UNIQUE INDEX `Date_naissance_UNIQUE` (`Date_of_birth` ASC) VISIBLE,
  UNIQUE INDEX `Date_of_death_UNIQUE` (`Date_of_death` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `idUSER` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `mobile` VARCHAR(45) NULL,
  `adress` VARCHAR(255) NULL,
  PRIMARY KEY (`idUSER`),
  UNIQUE INDEX `idUSER_UNIQUE` (`idUSER` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LIVRE_has_AUTEUR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LIVRE_has_AUTEUR` (
  `LIVRE_idLIVRE` INT NOT NULL,
  `AUTEUR_idAUTEUR` INT NOT NULL,
  PRIMARY KEY (`LIVRE_idLIVRE`, `AUTEUR_idAUTEUR`),
  INDEX `fk_LIVRE_has_AUTEUR_AUTEUR1_idx` (`AUTEUR_idAUTEUR` ASC) VISIBLE,
  INDEX `fk_LIVRE_has_AUTEUR_LIVRE1_idx` (`LIVRE_idLIVRE` ASC) VISIBLE,
  CONSTRAINT `fk_LIVRE_has_AUTEUR_LIVRE1`
    FOREIGN KEY (`LIVRE_idLIVRE`)
    REFERENCES `mydb`.`LIVRE` (`idLIVRE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIVRE_has_AUTEUR_AUTEUR1`
    FOREIGN KEY (`AUTEUR_idAUTEUR`)
    REFERENCES `mydb`.`AUTEUR` (`idAUTEUR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LIVRE_has_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LIVRE_has_USER` (
  `LIVRE_idLIVRE` INT NOT NULL,
  `USER_idUSER` INT NOT NULL,
  PRIMARY KEY (`LIVRE_idLIVRE`, `USER_idUSER`),
  INDEX `fk_LIVRE_has_USER_USER1_idx` (`USER_idUSER` ASC) VISIBLE,
  INDEX `fk_LIVRE_has_USER_LIVRE1_idx` (`LIVRE_idLIVRE` ASC) VISIBLE,
  CONSTRAINT `fk_LIVRE_has_USER_LIVRE1`
    FOREIGN KEY (`LIVRE_idLIVRE`)
    REFERENCES `mydb`.`LIVRE` (`idLIVRE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIVRE_has_USER_USER1`
    FOREIGN KEY (`USER_idUSER`)
    REFERENCES `mydb`.`USER` (`idUSER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
